CREATE TABLE applications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(80) NOT NULL,
  class VARCHAR(30) NOT NULL,
  contact VARCHAR(120) NOT NULL
);